server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Snow Leopard Chrome 49"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "49.0"
    "os": "osx"
    "os_version": "snow leopard"