#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        com_officeconnect_cmd_exec:
            enable: true
            category: ["Exploits", "Router"]
            name: "3COM OfficeConnect Command Execution"
            description: "Attempts to execute arbitrary commands on a 3Com OfficeConnect ADSL Wireless 11g Firewall Router (OSVDB# 66232).<br/>For more information see, <a href='https://www.andreafabrizi.it/2009/10/18/3COM-OfficeConnect-FirewallRouter-multiple-Vulnerabilities/'>https://www.andreafabrizi.it/2009/10/18/3COM-OfficeConnect-FirewallRouter-multiple-Vulnerabilities/</a>"
            authors: ["bcoles", "Andrea Fabrizi"]
            target:
                working: ["ALL"]
