#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
  module:
    edge_wscript_wsh_injection:
      enable: true
      category: ["Social Engineering"]
      name: "Edge WScript WSH Injection"
      description: "Prompts the user to run \"Microsoft Windows Based Script Host\" (WScript.exe).<br/><br/>Uses <a href='https://leucosite.com/Microsoft-Edge-RCE/'>wshfile protocol handler</a> technique to load pubprn.vbs and <a href='https://enigma0x3.net/2017/08/03/wsh-injection-a-case-study/'>WSH injection in pubprn.vbs</a> to execute arbitrary code.<br/><br/>If the user allows execution, a VBS payload is downloaded from BeEF, and the specified commands are executed."
      authors: [
        "@qab",       # wshfile protocol handler + traversal technique, and exploit
        "@enigma0x3", # pubprn.vbs technique and exploit
        "bcoles"      # BeEF
      ]
      target:
        user_notify: ["E"]
        not_working: ["ALL"]
