#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        admin_ui:
            name: 'Admin UI'
            enable: false

            # Authentication and authorisation
            session_cookie_name: "BEEFSESSION"
            login_fail_delay: 1

            # Admin UI
            base_path: "/ui"
            favicon_file_name: "favicon.ico"
            play_sound_on_new_zombie: false
            panel_update_interval: 10 # seconds

