#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        fake_flash_update:
            enable: true
            category: "Social Engineering"
            name: "Fake Flash Update"
            description: "Prompts the user to install an update to <b>Adobe Flash Player</b> from the specified URL."
            authors: ["mh", "antisnatchor", "gcattani"]
            target:
                user_notify: ['ALL']
