server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP IE 7"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "internet explorer"
    "browser_version": "7.0"
    "os": "windows"
    "os_version": "xp"