#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_opennic:
            enable: true
            category: "Network"
            name: "Detect OpenNIC DNS"
            description: "This module will detect if the zombie is currently using OpenNIC DNS resolvers.</br><br/>Note that the detection may fail when attempting to load a HTTP resource from a hooked HTTPS page."
            authors: ["wade", "pdp", "bm", "xntrik", "bcoles"]
            target:
                working: ["ALL"]
