#
# Copyright (c) 2006-2023 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        social_engineering:
            enable: false
            name: 'Social Engineering'
            authors: ["antisnatchor"]
            web_cloner:
                # NOTE: you must have 'wget' in your PATH
                add_beef_hook: true
                user_agent: "Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2"
                verify_ssl: true
            powershell:
                # the default payload being used is windows/meterpreter/reverse_https
                msf_reverse_handler_host: "172.16.45.1"
                msf_reverse_handler_port: "443"
                powershell_handler_url: "/ps"
